# Directories
DIR:
  DATASET: './dataset_sim_real/sim_v9/training'
  OUTPUT: './outputs_sim_real_7_22'

# Split files
SPLIT:
  VAL: './dataset_sim_real/sim_v9/training_lists/all.txt'
  LEFT: '0128_irL_denoised_half.png'
  RIGHT: '0128_irR_denoised_half.png'
  DEPTHL: 'depthL.png'
  DEPTHR: 'depthR.png'
  META: 'meta.pkl'

# Configuration for testing on real dataset
REAL:
  DATASET: './dataset_sim_real/real_v9'
  LEFT: '1024_irL_real_1080.png'
  RIGHT: '1024_irR_real_1080.png'

# Args
ARGS:
  MAX_DISP: 192