# Config files for local training

# Directories
DIR:
  DATASET: '/code/dataset_local_v9/training'  #  directory of your training dataset
  OUTPUT: '/code/outputs_sim_real'  # output folder to store all your results

# Split files
SPLIT:
  TRAIN: '/code/dataset_local_v9/training_lists/all_train.txt'  # training lists of your training dataset
  VAL: '/code/dataset_local_v9/training_lists/all_val.txt'  # training lists of your validation dataset
  LEFT: '0128_irL_denoised_half.png'
  RIGHT: '0128_irR_denoised_half.png'
  DEPTHL: 'depthL.png'
  DEPTHR: 'depthR.png'
  META: 'meta.pkl'
  LABEL: 'irL_label_image.png'

# Data Augmentation
DATA_AUG:
  # Color Jitter
  BRIGHT_MIN: 0.4
  BRIGHT_MAX: 1.4
  CONTRAST_MIN: 0.8
  CONTRAST_MAX: 1.2

  # Gaussian blur
  GAUSSIAN_MIN: 0.1
  GAUSSIAN_MAX: 2
  GAUSSIAN_KERNEL: 9